dbt_project:
  target: dev
  outputs:
    dev:
      dbname: ingest
      host: localhost
      password: ingest
      port: 5445
      schema: public
      threads: 1
      type: postgres
      user: ingest