dbt_project:
  target: dev
  outputs:
    dev:
      user: admin
      password: pass
      dbname: mydb
      host: localhost
      port: 5432
      schema: public
      threads: 1
      type: postgres